name: Terraform Format and Validate

on:
  workflow_dispatch:
    inputs:
      tf_directory:
        description: 'Terraform directory (e.g. infra/, terraform/dev)'
        required: true
        default: 'environments/dev'

jobs:
  terraform:
    name: Format and Validate Terraform Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.7

    - name: Terraform Format
      run: terraform fmt -check -diff

    - name: Terraform Validate
      run: terraform validate

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
